import mysql.connector as m
mycon=m.connect(host='localhost',user='root',passwd='deepak',database='college')
print(mycon.is_connected())
cur=mycon.cursor()
cur.execute('drop table student')
cur.execute('''create table student(RollNo integer primary key,Name varchar(30) not null,Course varchar(30),Phone_Number char(10),EmailID varchar(35),Fee varchar(10))''')
cur.execute('desc student')
for i in cur:
    print(i)
cur.execute('''insert into student(RollNo,Name,Course,Phone_Number,EmailID,Fee)
               values(605001,'Adithya','B.E.Computer Science','9765434560','adithya254@gmail.com','Paid')''')
cur.execute('''insert into student(RollNo,Name,Course,Phone_Number,EmailID,Fee)
               values(605002,'Aniruth','B.E.Mechanical','8455702345','AniRuth@gmail.com','Not Yet')''')
cur.execute('''insert into student(RollNo,Name,Course,Phone_Number,EmailID,Fee)
               values(605003,'Caroline','Aeronautical Engineering','9853450864','Carolineforbes@gmail.com','Paid')''')
cur.execute('''insert into student(RollNo,Name,Course,Phone_Number,EmailID,Fee)
               values(605004,'Damon Salvatore','Civil Engineering','9758346578','damonsalvator1839@gmail.com','Paid')''')
cur.execute('''insert into student(RollNo,Name,Course,Phone_Number,EmailID,Fee)
               values(605005,'Niklaus','B.E.Computer Science','7299375700','Hopeklaushayley@gmail.com','Paid')''')
mycon.commit()
cur.execute('select * from student')
for i in cur:
    print(i)
mycon.close()
